
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BLFacade", targetNamespace = "http://businessLogic/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BLFacade {


    /**
     * 
     * @param arg0
     * @return
     *     returns service.SaleSellerBoughtContainer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSaleSellerBoughtContainer", targetNamespace = "http://businessLogic/", className = "service.GetSaleSellerBoughtContainer")
    @ResponseWrapper(localName = "getSaleSellerBoughtContainerResponse", targetNamespace = "http://businessLogic/", className = "service.GetSaleSellerBoughtContainerResponse")
    @Action(input = "http://businessLogic/BLFacade/getSaleSellerBoughtContainerRequest", output = "http://businessLogic/BLFacade/getSaleSellerBoughtContainerResponse")
    public SaleSellerBoughtContainer getSaleSellerBoughtContainer(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns service.Sale
     * @throws FileNotUploadedException_Exception
     * @throws MustBeLaterThanTodayException_Exception
     * @throws SaleAlreadyExistException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSale", targetNamespace = "http://businessLogic/", className = "service.CreateSale")
    @ResponseWrapper(localName = "createSaleResponse", targetNamespace = "http://businessLogic/", className = "service.CreateSaleResponse")
    @Action(input = "http://businessLogic/BLFacade/createSaleRequest", output = "http://businessLogic/BLFacade/createSaleResponse", fault = {
        @FaultAction(className = FileNotUploadedException_Exception.class, value = "http://businessLogic/BLFacade/createSale/Fault/FileNotUploadedException"),
        @FaultAction(className = MustBeLaterThanTodayException_Exception.class, value = "http://businessLogic/BLFacade/createSale/Fault/MustBeLaterThanTodayException"),
        @FaultAction(className = SaleAlreadyExistException_Exception.class, value = "http://businessLogic/BLFacade/createSale/Fault/SaleAlreadyExistException")
    })
    public Sale createSale(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        float arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6)
        throws FileNotUploadedException_Exception, MustBeLaterThanTodayException_Exception, SaleAlreadyExistException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @throws ErreklamazioaAlreadyExistException_Exception
     * @throws MustBeLaterThanTodayException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "erreklamazioaSortu", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaSortu")
    @ResponseWrapper(localName = "erreklamazioaSortuResponse", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaSortuResponse")
    @Action(input = "http://businessLogic/BLFacade/erreklamazioaSortuRequest", output = "http://businessLogic/BLFacade/erreklamazioaSortuResponse", fault = {
        @FaultAction(className = MustBeLaterThanTodayException_Exception.class, value = "http://businessLogic/BLFacade/erreklamazioaSortu/Fault/MustBeLaterThanTodayException"),
        @FaultAction(className = ErreklamazioaAlreadyExistException_Exception.class, value = "http://businessLogic/BLFacade/erreklamazioaSortu/Fault/ErreklamazioaAlreadyExistException")
    })
    public void erreklamazioaSortu(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        BoughtSale arg5)
        throws ErreklamazioaAlreadyExistException_Exception, MustBeLaterThanTodayException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Sale>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSales", targetNamespace = "http://businessLogic/", className = "service.GetSales")
    @ResponseWrapper(localName = "getSalesResponse", targetNamespace = "http://businessLogic/", className = "service.GetSalesResponse")
    @Action(input = "http://businessLogic/BLFacade/getSalesRequest", output = "http://businessLogic/BLFacade/getSalesResponse")
    public List<Sale> getSales(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<service.Sale>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPublishedSales", targetNamespace = "http://businessLogic/", className = "service.GetPublishedSales")
    @ResponseWrapper(localName = "getPublishedSalesResponse", targetNamespace = "http://businessLogic/", className = "service.GetPublishedSalesResponse")
    @Action(input = "http://businessLogic/BLFacade/getPublishedSalesRequest", output = "http://businessLogic/BLFacade/getPublishedSalesResponse")
    public List<Sale> getPublishedSales(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "initializeBD", targetNamespace = "http://businessLogic/", className = "service.InitializeBD")
    @ResponseWrapper(localName = "initializeBDResponse", targetNamespace = "http://businessLogic/", className = "service.InitializeBDResponse")
    @Action(input = "http://businessLogic/BLFacade/initializeBDRequest", output = "http://businessLogic/BLFacade/initializeBDResponse")
    public void initializeBD();

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadImage", targetNamespace = "http://businessLogic/", className = "service.DownloadImage")
    @ResponseWrapper(localName = "downloadImageResponse", targetNamespace = "http://businessLogic/", className = "service.DownloadImageResponse")
    @Action(input = "http://businessLogic/BLFacade/downloadImageRequest", output = "http://businessLogic/BLFacade/downloadImageResponse")
    public byte[] downloadImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isLogged", targetNamespace = "http://businessLogic/", className = "service.IsLogged")
    @ResponseWrapper(localName = "isLoggedResponse", targetNamespace = "http://businessLogic/", className = "service.IsLoggedResponse")
    @Action(input = "http://businessLogic/BLFacade/isLoggedRequest", output = "http://businessLogic/BLFacade/isLoggedResponse")
    public User isLogged(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns service.Registered
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "erabiltzaileaSortu", targetNamespace = "http://businessLogic/", className = "service.ErabiltzaileaSortu")
    @ResponseWrapper(localName = "erabiltzaileaSortuResponse", targetNamespace = "http://businessLogic/", className = "service.ErabiltzaileaSortuResponse")
    @Action(input = "http://businessLogic/BLFacade/erabiltzaileaSortuRequest", output = "http://businessLogic/BLFacade/erabiltzaileaSortuResponse")
    public Registered erabiltzaileaSortu(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "faboritoaEzabatu", targetNamespace = "http://businessLogic/", className = "service.FaboritoaEzabatu")
    @ResponseWrapper(localName = "faboritoaEzabatuResponse", targetNamespace = "http://businessLogic/", className = "service.FaboritoaEzabatuResponse")
    @Action(input = "http://businessLogic/BLFacade/faboritoaEzabatuRequest", output = "http://businessLogic/BLFacade/faboritoaEzabatuResponse")
    public boolean faboritoaEzabatu(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "faboritoaGehitu", targetNamespace = "http://businessLogic/", className = "service.FaboritoaGehitu")
    @ResponseWrapper(localName = "faboritoaGehituResponse", targetNamespace = "http://businessLogic/", className = "service.FaboritoaGehituResponse")
    @Action(input = "http://businessLogic/BLFacade/faboritoaGehituRequest", output = "http://businessLogic/BLFacade/faboritoaGehituResponse")
    public boolean faboritoaGehitu(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "erositakoaGehitu", targetNamespace = "http://businessLogic/", className = "service.ErositakoaGehitu")
    @ResponseWrapper(localName = "erositakoaGehituResponse", targetNamespace = "http://businessLogic/", className = "service.ErositakoaGehituResponse")
    @Action(input = "http://businessLogic/BLFacade/erositakoaGehituRequest", output = "http://businessLogic/BLFacade/erositakoaGehituResponse")
    public void erositakoaGehitu(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "faboritoaDa", targetNamespace = "http://businessLogic/", className = "service.FaboritoaDa")
    @ResponseWrapper(localName = "faboritoaDaResponse", targetNamespace = "http://businessLogic/", className = "service.FaboritoaDaResponse")
    @Action(input = "http://businessLogic/BLFacade/faboritoaDaRequest", output = "http://businessLogic/BLFacade/faboritoaDaResponse")
    public boolean faboritoaDa(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Registered
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSellerByName", targetNamespace = "http://businessLogic/", className = "service.GetSellerByName")
    @ResponseWrapper(localName = "getSellerByNameResponse", targetNamespace = "http://businessLogic/", className = "service.GetSellerByNameResponse")
    @Action(input = "http://businessLogic/BLFacade/getSellerByNameRequest", output = "http://businessLogic/BLFacade/getSellerByNameResponse")
    public Registered getSellerByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Registered
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSellerByEmail", targetNamespace = "http://businessLogic/", className = "service.GetSellerByEmail")
    @ResponseWrapper(localName = "getSellerByEmailResponse", targetNamespace = "http://businessLogic/", className = "service.GetSellerByEmailResponse")
    @Action(input = "http://businessLogic/BLFacade/getSellerByEmailRequest", output = "http://businessLogic/BLFacade/getSellerByEmailResponse")
    public Registered getSellerByEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Sale>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFaboritoak", targetNamespace = "http://businessLogic/", className = "service.GetFaboritoak")
    @ResponseWrapper(localName = "getFaboritoakResponse", targetNamespace = "http://businessLogic/", className = "service.GetFaboritoakResponse")
    @Action(input = "http://businessLogic/BLFacade/getFaboritoakRequest", output = "http://businessLogic/BLFacade/getFaboritoakResponse")
    public List<Sale> getFaboritoak(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.BoughtSale>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getErositakoak", targetNamespace = "http://businessLogic/", className = "service.GetErositakoak")
    @ResponseWrapper(localName = "getErositakoakResponse", targetNamespace = "http://businessLogic/", className = "service.GetErositakoakResponse")
    @Action(input = "http://businessLogic/BLFacade/getErositakoakRequest", output = "http://businessLogic/BLFacade/getErositakoakResponse")
    public List<BoughtSale> getErositakoak(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns service.BoughtSale
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lortuErositakoSalmenta", targetNamespace = "http://businessLogic/", className = "service.LortuErositakoSalmenta")
    @ResponseWrapper(localName = "lortuErositakoSalmentaResponse", targetNamespace = "http://businessLogic/", className = "service.LortuErositakoSalmentaResponse")
    @Action(input = "http://businessLogic/BLFacade/lortuErositakoSalmentaRequest", output = "http://businessLogic/BLFacade/lortuErositakoSalmentaResponse")
    public BoughtSale lortuErositakoSalmenta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "produktoaErosi", targetNamespace = "http://businessLogic/", className = "service.ProduktoaErosi")
    @ResponseWrapper(localName = "produktoaErosiResponse", targetNamespace = "http://businessLogic/", className = "service.ProduktoaErosiResponse")
    @Action(input = "http://businessLogic/BLFacade/produktoaErosiRequest", output = "http://businessLogic/BLFacade/produktoaErosiResponse")
    public boolean produktoaErosi(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<service.Sale>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSalesBySeller", targetNamespace = "http://businessLogic/", className = "service.GetSalesBySeller")
    @ResponseWrapper(localName = "getSalesBySellerResponse", targetNamespace = "http://businessLogic/", className = "service.GetSalesBySellerResponse")
    @Action(input = "http://businessLogic/BLFacade/getSalesBySellerRequest", output = "http://businessLogic/BLFacade/getSalesBySellerResponse")
    public List<Sale> getSalesBySeller(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<service.BoughtSale>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSoldBySeller", targetNamespace = "http://businessLogic/", className = "service.GetSoldBySeller")
    @ResponseWrapper(localName = "getSoldBySellerResponse", targetNamespace = "http://businessLogic/", className = "service.GetSoldBySellerResponse")
    @Action(input = "http://businessLogic/BLFacade/getSoldBySellerRequest", output = "http://businessLogic/BLFacade/getSoldBySellerResponse")
    public List<BoughtSale> getSoldBySeller(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeSale", targetNamespace = "http://businessLogic/", className = "service.RemoveSale")
    @ResponseWrapper(localName = "removeSaleResponse", targetNamespace = "http://businessLogic/", className = "service.RemoveSaleResponse")
    @Action(input = "http://businessLogic/BLFacade/removeSaleRequest", output = "http://businessLogic/BLFacade/removeSaleResponse")
    public boolean removeSale(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "diruaAtera", targetNamespace = "http://businessLogic/", className = "service.DiruaAtera")
    @ResponseWrapper(localName = "diruaAteraResponse", targetNamespace = "http://businessLogic/", className = "service.DiruaAteraResponse")
    @Action(input = "http://businessLogic/BLFacade/diruaAteraRequest", output = "http://businessLogic/BLFacade/diruaAteraResponse")
    public boolean diruaAtera(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "diruaSartu", targetNamespace = "http://businessLogic/", className = "service.DiruaSartu")
    @ResponseWrapper(localName = "diruaSartuResponse", targetNamespace = "http://businessLogic/", className = "service.DiruaSartuResponse")
    @Action(input = "http://businessLogic/BLFacade/diruaSartuRequest", output = "http://businessLogic/BLFacade/diruaSartuResponse")
    public void diruaSartu(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<service.Mugimendua>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMugimenduakBySeller", targetNamespace = "http://businessLogic/", className = "service.GetMugimenduakBySeller")
    @ResponseWrapper(localName = "getMugimenduakBySellerResponse", targetNamespace = "http://businessLogic/", className = "service.GetMugimenduakBySellerResponse")
    @Action(input = "http://businessLogic/BLFacade/getMugimenduakBySellerRequest", output = "http://businessLogic/BLFacade/getMugimenduakBySellerResponse")
    public List<Mugimendua> getMugimenduakBySeller(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns service.Erreklamazioa
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lortuErreklamazioa", targetNamespace = "http://businessLogic/", className = "service.LortuErreklamazioa")
    @ResponseWrapper(localName = "lortuErreklamazioaResponse", targetNamespace = "http://businessLogic/", className = "service.LortuErreklamazioaResponse")
    @Action(input = "http://businessLogic/BLFacade/lortuErreklamazioaRequest", output = "http://businessLogic/BLFacade/lortuErreklamazioaResponse")
    public Erreklamazioa lortuErreklamazioa(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns service.Erreklamazioa
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "disputaMezuaGehitu", targetNamespace = "http://businessLogic/", className = "service.DisputaMezuaGehitu")
    @ResponseWrapper(localName = "disputaMezuaGehituResponse", targetNamespace = "http://businessLogic/", className = "service.DisputaMezuaGehituResponse")
    @Action(input = "http://businessLogic/BLFacade/disputaMezuaGehituRequest", output = "http://businessLogic/BLFacade/disputaMezuaGehituResponse")
    public Erreklamazioa disputaMezuaGehitu(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns service.Erreklamazioa
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "erreklamazioaEgoeraAldatu", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaEgoeraAldatu")
    @ResponseWrapper(localName = "erreklamazioaEgoeraAldatuResponse", targetNamespace = "http://businessLogic/", className = "service.ErreklamazioaEgoeraAldatuResponse")
    @Action(input = "http://businessLogic/BLFacade/erreklamazioaEgoeraAldatuRequest", output = "http://businessLogic/BLFacade/erreklamazioaEgoeraAldatuResponse")
    public Erreklamazioa erreklamazioaEgoeraAldatu(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @return
     *     returns java.util.List<service.Erreklamazioa>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getErreklamazioEskalatuak", targetNamespace = "http://businessLogic/", className = "service.GetErreklamazioEskalatuak")
    @ResponseWrapper(localName = "getErreklamazioEskalatuakResponse", targetNamespace = "http://businessLogic/", className = "service.GetErreklamazioEskalatuakResponse")
    @Action(input = "http://businessLogic/BLFacade/getErreklamazioEskalatuakRequest", output = "http://businessLogic/BLFacade/getErreklamazioEskalatuakResponse")
    public List<Erreklamazioa> getErreklamazioEskalatuak();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "notifikazioaBidali", targetNamespace = "http://businessLogic/", className = "service.NotifikazioaBidali")
    @ResponseWrapper(localName = "notifikazioaBidaliResponse", targetNamespace = "http://businessLogic/", className = "service.NotifikazioaBidaliResponse")
    @Action(input = "http://businessLogic/BLFacade/notifikazioaBidaliRequest", output = "http://businessLogic/BLFacade/notifikazioaBidaliResponse")
    public void notifikazioaBidali(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "badituIrakurriGabekoak", targetNamespace = "http://businessLogic/", className = "service.BadituIrakurriGabekoak")
    @ResponseWrapper(localName = "badituIrakurriGabekoakResponse", targetNamespace = "http://businessLogic/", className = "service.BadituIrakurriGabekoakResponse")
    @Action(input = "http://businessLogic/BLFacade/badituIrakurriGabekoakRequest", output = "http://businessLogic/BLFacade/badituIrakurriGabekoakResponse")
    public boolean badituIrakurriGabekoak(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "markatuIrakurrita", targetNamespace = "http://businessLogic/", className = "service.MarkatuIrakurrita")
    @ResponseWrapper(localName = "markatuIrakurritaResponse", targetNamespace = "http://businessLogic/", className = "service.MarkatuIrakurritaResponse")
    @Action(input = "http://businessLogic/BLFacade/markatuIrakurritaRequest", output = "http://businessLogic/BLFacade/markatuIrakurritaResponse")
    public void markatuIrakurrita(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Notifikazioa>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNotifikazioak", targetNamespace = "http://businessLogic/", className = "service.GetNotifikazioak")
    @ResponseWrapper(localName = "getNotifikazioakResponse", targetNamespace = "http://businessLogic/", className = "service.GetNotifikazioakResponse")
    @Action(input = "http://businessLogic/BLFacade/getNotifikazioakRequest", output = "http://businessLogic/BLFacade/getNotifikazioakResponse")
    public List<Notifikazioa> getNotifikazioak(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws MustBeLaterThanTodayException_Exception
     * @throws ErreklamazioaAlreadyExistException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "salaketaSortu", targetNamespace = "http://businessLogic/", className = "service.SalaketaSortu")
    @ResponseWrapper(localName = "salaketaSortuResponse", targetNamespace = "http://businessLogic/", className = "service.SalaketaSortuResponse")
    @Action(input = "http://businessLogic/BLFacade/salaketaSortuRequest", output = "http://businessLogic/BLFacade/salaketaSortuResponse", fault = {
        @FaultAction(className = MustBeLaterThanTodayException_Exception.class, value = "http://businessLogic/BLFacade/salaketaSortu/Fault/MustBeLaterThanTodayException"),
        @FaultAction(className = ErreklamazioaAlreadyExistException_Exception.class, value = "http://businessLogic/BLFacade/salaketaSortu/Fault/ErreklamazioaAlreadyExistException")
    })
    public void salaketaSortu(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Registered arg3)
        throws ErreklamazioaAlreadyExistException_Exception, MustBeLaterThanTodayException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<service.Salaketa>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSalaketak", targetNamespace = "http://businessLogic/", className = "service.GetSalaketak")
    @ResponseWrapper(localName = "getSalaketakResponse", targetNamespace = "http://businessLogic/", className = "service.GetSalaketakResponse")
    @Action(input = "http://businessLogic/BLFacade/getSalaketakRequest", output = "http://businessLogic/BLFacade/getSalaketakResponse")
    public List<Salaketa> getSalaketak();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "produktoaEzabatu", targetNamespace = "http://businessLogic/", className = "service.ProduktoaEzabatu")
    @ResponseWrapper(localName = "produktoaEzabatuResponse", targetNamespace = "http://businessLogic/", className = "service.ProduktoaEzabatuResponse")
    @Action(input = "http://businessLogic/BLFacade/produktoaEzabatuRequest", output = "http://businessLogic/BLFacade/produktoaEzabatuResponse")
    public void produktoaEzabatu(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "kontuaBaneatu", targetNamespace = "http://businessLogic/", className = "service.KontuaBaneatu")
    @ResponseWrapper(localName = "kontuaBaneatuResponse", targetNamespace = "http://businessLogic/", className = "service.KontuaBaneatuResponse")
    @Action(input = "http://businessLogic/BLFacade/kontuaBaneatuRequest", output = "http://businessLogic/BLFacade/kontuaBaneatuResponse")
    public void kontuaBaneatu(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "kontuaDesbaneatu", targetNamespace = "http://businessLogic/", className = "service.KontuaDesbaneatu")
    @ResponseWrapper(localName = "kontuaDesbaneatuResponse", targetNamespace = "http://businessLogic/", className = "service.KontuaDesbaneatuResponse")
    @Action(input = "http://businessLogic/BLFacade/kontuaDesbaneatuRequest", output = "http://businessLogic/BLFacade/kontuaDesbaneatuResponse")
    public void kontuaDesbaneatu(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Registered>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegisteredUsers", targetNamespace = "http://businessLogic/", className = "service.GetRegisteredUsers")
    @ResponseWrapper(localName = "getRegisteredUsersResponse", targetNamespace = "http://businessLogic/", className = "service.GetRegisteredUsersResponse")
    @Action(input = "http://businessLogic/BLFacade/getRegisteredUsersRequest", output = "http://businessLogic/BLFacade/getRegisteredUsersResponse")
    public List<Registered> getRegisteredUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "salaketaEgoeraAldatu", targetNamespace = "http://businessLogic/", className = "service.SalaketaEgoeraAldatu")
    @ResponseWrapper(localName = "salaketaEgoeraAldatuResponse", targetNamespace = "http://businessLogic/", className = "service.SalaketaEgoeraAldatuResponse")
    @Action(input = "http://businessLogic/BLFacade/salaketaEgoeraAldatuRequest", output = "http://businessLogic/BLFacade/salaketaEgoeraAldatuResponse")
    public void salaketaEgoeraAldatu(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "salatutaDago", targetNamespace = "http://businessLogic/", className = "service.SalatutaDago")
    @ResponseWrapper(localName = "salatutaDagoResponse", targetNamespace = "http://businessLogic/", className = "service.SalatutaDagoResponse")
    @Action(input = "http://businessLogic/BLFacade/salatutaDagoRequest", output = "http://businessLogic/BLFacade/salatutaDagoResponse")
    public boolean salatutaDago(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSellerByErreklamazioa", targetNamespace = "http://businessLogic/", className = "service.GetSellerByErreklamazioa")
    @ResponseWrapper(localName = "getSellerByErreklamazioaResponse", targetNamespace = "http://businessLogic/", className = "service.GetSellerByErreklamazioaResponse")
    @Action(input = "http://businessLogic/BLFacade/getSellerByErreklamazioaRequest", output = "http://businessLogic/BLFacade/getSellerByErreklamazioaResponse")
    public User getSellerByErreklamazioa(
        @WebParam(name = "arg0", targetNamespace = "")
        Erreklamazioa arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBuyerByErreklamazioa", targetNamespace = "http://businessLogic/", className = "service.GetBuyerByErreklamazioa")
    @ResponseWrapper(localName = "getBuyerByErreklamazioaResponse", targetNamespace = "http://businessLogic/", className = "service.GetBuyerByErreklamazioaResponse")
    @Action(input = "http://businessLogic/BLFacade/getBuyerByErreklamazioaRequest", output = "http://businessLogic/BLFacade/getBuyerByErreklamazioaResponse")
    public User getBuyerByErreklamazioa(
        @WebParam(name = "arg0", targetNamespace = "")
        Erreklamazioa arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSalatzaileaBySalaketa", targetNamespace = "http://businessLogic/", className = "service.GetSalatzaileaBySalaketa")
    @ResponseWrapper(localName = "getSalatzaileaBySalaketaResponse", targetNamespace = "http://businessLogic/", className = "service.GetSalatzaileaBySalaketaResponse")
    @Action(input = "http://businessLogic/BLFacade/getSalatzaileaBySalaketaRequest", output = "http://businessLogic/BLFacade/getSalatzaileaBySalaketaResponse")
    public User getSalatzaileaBySalaketa(
        @WebParam(name = "arg0", targetNamespace = "")
        Salaketa arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIgorleaByDM", targetNamespace = "http://businessLogic/", className = "service.GetIgorleaByDM")
    @ResponseWrapper(localName = "getIgorleaByDMResponse", targetNamespace = "http://businessLogic/", className = "service.GetIgorleaByDMResponse")
    @Action(input = "http://businessLogic/BLFacade/getIgorleaByDMRequest", output = "http://businessLogic/BLFacade/getIgorleaByDMResponse")
    public User getIgorleaByDM(
        @WebParam(name = "arg0", targetNamespace = "")
        DisputaMezua arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Erreklamazioa
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lortuErreklamazioById", targetNamespace = "http://businessLogic/", className = "service.LortuErreklamazioById")
    @ResponseWrapper(localName = "lortuErreklamazioByIdResponse", targetNamespace = "http://businessLogic/", className = "service.LortuErreklamazioByIdResponse")
    @Action(input = "http://businessLogic/BLFacade/lortuErreklamazioByIdRequest", output = "http://businessLogic/BLFacade/lortuErreklamazioByIdResponse")
    public Erreklamazioa lortuErreklamazioById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
