
package service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ErreklamazioaAlreadyExistException", targetNamespace = "http://businessLogic/")
public class ErreklamazioaAlreadyExistException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErreklamazioaAlreadyExistException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ErreklamazioaAlreadyExistException_Exception(String message, ErreklamazioaAlreadyExistException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ErreklamazioaAlreadyExistException_Exception(String message, ErreklamazioaAlreadyExistException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: service.ErreklamazioaAlreadyExistException
     */
    public ErreklamazioaAlreadyExistException getFaultInfo() {
        return faultInfo;
    }

}
