
package service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FileNotUploadedException", targetNamespace = "http://businessLogic/")
public class FileNotUploadedException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FileNotUploadedException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FileNotUploadedException_Exception(String message, FileNotUploadedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FileNotUploadedException_Exception(String message, FileNotUploadedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: service.FileNotUploadedException
     */
    public FileNotUploadedException getFaultInfo() {
        return faultInfo;
    }

}
