Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu
MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak konstsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Merkatua
MainGUI.Login=Logeatu
MainGUI.Register=Erregistratu
MainGUI.Favorites=Faboritoak
MainGUI.Unregistered=Ez erregistratua

MainGUIerregistratua.Logout=Amaitua Saioa
MainGUIerregistratua.Perfila=Profila
MainGUIerregistratua.YourSales=Zure Produktuak

MainGUIAdmin.Salaketak=Salaketak
MainGUIAdmin.Erreklamazioak=Erreklamazioak
MainGUIAdmin.ProduktuakKontsultatu=Produktuak
MainGUIAdmin.ErabiltzaileakKontsultatu=Erabiltzaile zerrenda
MainGUIAdmin.MezuakBidali=Mezua Bidali

FavoritoGUI.EzabatutakoFaboritoKop=  Produktua(k) ezabatua(k)
FavoritoGUI.EzDagoEzerAukeratuta=Ez duzu ezer aukeratu!
FaboritoGUI.FindProducts=Produktu faboritoak bilatu


LoginGUI.Title=Saioa Hasi
LoginGUI.User=Email
LoginGUI.Pass=Pasahitza
LoginGUI.Button=Saioa Hasi
LoginGUI.Error=Email edo pasahitz okerrak
LoginGUI.Error2=Datuak falta dira
LoginGUI.btnAtzera=Atzera


RegisterGUI.Title=ERREGISTRATU
RegisterGUI.Email=Email
RegisterGUI.User=Erabiltzailea
RegisterGUI.Pass1=Pasahitza
RegisterGUI.Pass2=Pasahitza errepikatu
RegisterGUI.Button=ERREGISTRATU
RegisterGUI.Error1=Erabiltzailea existitzen da
RegisterGUI.Error2=Pasahitzak desberdinak dira
RegisterGUI.btnAtzera=Atzera


CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorImage=Error, irudi bat egon behar da.
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna
CreateSaleGUI.Create=Produktoa sortuta!

ErositakoakGUI.BoughtDate=Erositako eguna
ErositakoakGUI.FindProducts=Erositako produktuak bilatu


QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez dago produkturik
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)
QuerySalesGUI.btnAtzera=Atzera
QuerySalesGUI.RemoveFav=Faboritotatik kendu
QuerySalesGUI.FaboritoakKenduta=Faborito ezabatuta

ShowSaleGUI.Title=Eskaintza xehestasunak
ShowSaleGUI.Buy=Erosi
ShowSaleGUI.UpdateFav=Faboritoa Eguneratu
ShowSaleGUI.ImageError=Irudirik gabe
ShowSaleGUI.BuyMessage=Produktua erosita!
ShowSaleGUI.BuyTitle=Produktua erosita
ShowSaleGUI.BuyError=Produktu hau zurea da iada!
ShowSaleGUI.BuyErrorTitle=Zure produktua da
ShowSaleGUI.DeleteProduct=Produktua ezabatu
ShowSaleGUI.ProductDeleted=Produktua behar bezala ezabatu da
ShowSaleGUI.DeleteProductTitle=Produktua ezabatu
ShowSaleGUI.ProductIsYoursReport=Ezin duzu zure produktua salatu
ShowSaleGUI.ReportProductTitle=Produktua salatu
ShowSaleGUI.Reported=Salatuta
ShowSaleGUI.CancelReport=Salaketa ezeztatu

ShowYourSaleGUI.RemovedProduct=Produktua ezabatua!
ShowYourSaleGUI.RemoveProductTitle=Ezabatu produktua

DiruaKudeatuGUI.Error1=Formatu desegokia edo datuak falta diraLoginGUI.btnAtzera
DiruaKudeatuGUI.Error1Title=Informazio errorea
DiruaKudeatuGUI.Ondo=Eragiketa arrakastaz burutu da
DiruaKudeatuGUI.OndoTitle=Arrakasta
DiruaKudeatuGUI.Error2=Ez dago diru naikorik kontuan
DiruaKudeatuGUI.Error2Title=Diru nahikorik ez
DiruaKudeatuGUI.DiruKudeaketa=Diru Kudeaketa
DiruaKudeatuGUI.Datuak=Datuak
DiruaKudeatuGUI.Kantitatea=Kantitatea
DiruaKudeatuGUI.TxartelZbk=Txartel Zbk
DiruaKudeatuGUI.Txartela16Digito=Txartela (16 digitu)
DiruaKudeatuGUI.Ekintza=Ekintza
DiruaKudeatuGUI.DiruaAtera=Dirua Atera
DiruaKudeatuGUI.DiruaSartu=Dirua Sartu
DiruaKudeatuGUI.Continue=Jarraitu

PerfilaGUI.Historialak=HISTORIALAK
PerfilaGUI.Erositakoak=EROSITAKOAK
PerfilaGUI.Saldutakoak=SALDUTAKOAK
PerfilaGUI.DiruKudeaketa=DIRU-KUDEAKETA
PerfilaGUI.DiruaSartuAtera=DIRUA SARTU / ATERA
PerfilaGUI.Mugimenduak=MUGIMENDUAK
PerfilaGUI.Saldo=Zure dirua
PerfilaGUI.MainTitle=Perfila
PerfilaGUI.Buzoia=BUZOIA / MEZUAK

SalaketaGUI.Reportar=SALATU
SalaketaGUI.SalaketaBidali=Salaketa bidali da!
SalaketaGUI.Salaketa=SALAKETA
SalaketaGUI.Mota1=Pertsonak edo Animaliak
SalaketaGUI.Mota2=Txantxa
SalaketaGUI.Mota3=Produktu Faltsua
SalaketaGUI.Mota4=Eduki esplizitua
SalaketaGUI.Mota5=Argazkia ez dator bat
SalaketaGUI.Mota6=Janaria edo edariak
SalaketaGUI.Mota7=Produktu bikoiztua
SalaketaGUI.Mota8=Debekatutako produktu edo zerbitzua
SalaketaGUI.Mota9=Birsalmenta(sarrerak, etab.)
SalaketaGUI.Mota10=Publizitatea edo Spam

ErreklamatuGUI.Erreklamatu=ERREKLAMATU
ErreklamatuGUI.ErreklamazioaBidali=Salaketa bidali da!
ErreklamatuGUI.Erreklamazioa=ERREKLAMAZIOA

ErreklamazioHariaGUI.Erreklamazioa=Erreklamazio-Haria

ErreklamazioakAdminGUI.Titulua=Titulua
ErreklamazioakAdminGUI.Eroslea=Eroslea
ErreklamazioakAdminGUI.Saltzailea=Saltzailea
ErreklamazioakAdminGUI.Erreklamazioak=Erreklamazioak
ErreklamazioakAdminGUI.ErreklamazioakTitle=Ondorioztatu gabeko erreklamazioak

BuzoiaGUI.Jakinarazpenak=Nire Jakinarazpenak
BuzoiaGUI.Data=Data
BuzoiaGUI.Mezua=Mezua
BuzoiaGUI.BuzoiaJakinarazpenak=Buzoia - Jakinarazpenak

DiruaKudeatuGUI.DiruKudeaketa=DIRUA KUDEATU
DiruaKudeatuGUI.Datuak=DATUAK
DiruaKudeatuGUI.Kantitatea=Kantitatea
DiruaKudeatuGUI.TxartelZbk=Txartel zenbakia
DiruaKudeatuGUI.KantitateaIkurrikGabe=Kantitatea (ikurrik gabe)
DiruaKudeatuGUI.Txartela16Digito=Txartela (16 digito)
DiruaKudeatuGUI.Ekintza=Ekintza
DiruaKudeatuGUI.DiruaAtera=Dirua Atera
DiruaKudeatuGUI.DiruaSartu=Dirua Sartu

ErositakoaShowSaleGUI.ArgazkiaEzAurkitu=ez da default.jpg argazkia aurkitu
ErositakoaShowSaleGUI.EzDagoErreklamaziorik=Ez dago erreklamaziorik
ErositakoaShowSaleGUI.IkusiErreklamazioa=IKUSI ERREKLAMAZIOA

SaldutakoakGUI.SoldDate=Saldu data


SalaketakAdminGUI.SalaketaMota=Salaketa mota
ErreklamazioakAdminGUI.Saltzailea=Saltzailea
ErreklamazioakAdminGUI.Salatzailea=Salatzailea
BuzoiaGUI.Data=Data
ErreklamazioakAdminGUI.Titulua=Titulua
ErreklamazioakAdminGUI.SalaketaZerrenda=Salaketen zerrenda
SalaketakAdminGUI.Title=Salaketen kudeaketa
LoginGUI.btnAtzera=Atzera

QueryUsersAdminGUI.Izena=Izena
QueryUsersAdminGUI.EzErabiltzaile=Ez da erabiltzailerik aurkitu
MainGUIAdmin.ErabiltzaileakKontsultatu=Erabiltzaileak kontsultatu
RegisterGUI.Email=Emaila
QuerySalesGUI.Products=Erabiltzaileak
QuerySalesGUI.Search=Bilatu
QuerySalesGUI.btnAtzera=Atzera

NotifikazioaBidaliGUI.Title=Notifikazioa bidali
NotifikazioaBidaliGUI.Header=Notifikazioa erabiltzaileei bidali
NotifikazioaBidaliGUI.Recipient=Hartzailea
NotifikazioaBidaliGUI.SendToAll=Denei bidali
NotifikazioaBidaliGUI.Message=Mezua
NotifikazioaBidaliGUI.Send=Bidali
NotifikazioaBidaliGUI.Back=Atzera
NotifikazioaBidaliGUI.ErrorEmpty=Mezua ezin da hutsik egon
NotifikazioaBidaliGUI.Error=Errorea
NotifikazioaBidaliGUI.SuccessAll=Notifikazioa erabiltzaile guztiei bidali da
NotifikazioaBidaliGUI.SuccessSingle1=Notifikazioa bidali da hurrengori: 
NotifikazioaBidaliGUI.SuccessSingle2=

ShowRegisteredGUI.Name=Izena
ShowRegisteredGUI.Email=Emaila
ShowRegisteredGUI.ProductList=Produktuen zerrenda
ShowRegisteredGUI.BanAccount=Kontua baneatu
ShowRegisteredGUI.Unban=Desbaneatu
ShowRegisteredGUI.AccountBannedMsg=Kontua baneatu da ondo
ShowRegisteredGUI.AccountUnbannedMsg=Kontua desbaneatu da ondo
ShowRegisteredGUI.BanAccountTitle=Kontua Baneatua
ShowRegisteredGUI.UnbanAccountTitle=Kontua Desbaneatua

MugimenduakGUI.DiruSarrera=Diru Sarrera
MugimenduakGUI.DiruIrteera=Diru Irteera
DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da

ErreklamazioHariaGUI.ErreklamazioHaria=Erreklamazio haria
ErreklamazioHariaGUI.Erreklamazioa=Erreklamazioa
CreateSaleGUI.Status=Egoera
ErreklamazioHariaGUI.Bidali=Bidali
ErreklamazioHariaGUI.AdminAbisatu=Administratzailea abisatu
ErreklamazioHariaGUI.Onartu=Onartu itzulketa
ErreklamazioHariaGUI.ArrazoiaI=Eroslearen alde
ErreklamazioHariaGUI.ArrazoiaU=Saltzailearen alde
ErreklamazioHariaGUI.DiruaItzuli=Dirua itzuli da
ErreklamazioHariaGUI.Ukatu=Erreklamazioa ukatua
ErreklamazioHariaGUI.EskalatuNahi=Erreklamazioa administratzaileari eskalatu nahi duzu?
ErreklamazioHariaGUI.Eskalatu=Eskalatu
ErreklamazioHariaGUI.AdminAbixatua=Administratzailea abisatua
ErreklamazioHariaGUI.OnartuNahi=Itzulketa onartu nahi duzu?
ErreklamazioHariaGUI.Onartua=Itzulketa onartua
ErreklamazioHariaGUI.EzAurkitu=Erosketarik ez aurkitu
ErreklamazioHariaGUI.Error=Errorea
ErreklamazioHariaGUI.Produktua=Produktua ikusi
ErreklamazioHariaGUI.EzinMezua=Txata itxita
ErreklamazioHariaGUI.Enegoziatzen=Negoziatzen
ErreklamazioHariaGUI.Eitxaroten=Administratzailearen zain
ErreklamazioHariaGUI.Eonartua=Itzulketa onartua
ErreklamazioHariaGUI.Eukatua=Itzulketa ukatua
LoginGUI.btnAtzera=Atzera

DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da